export const IMAGE = {
  splash: require("../../assets/finalSplash.png"),
  back: require("./back_icon.png"),
  logo: require("./logo.png"),
  news: require("./news.png"),
  calender: require("./calendar.png"),
  product: require("./product.png"),
  profile: require("./profile.png"),
  new_appo: require("./new_appo.png"),
  check: require("./check.png"),
  menu: require("./menu-select.png"),
  home: require("./home.png"),
  propic_place: require("./propic_place.png"),
  next: require("./next.png"),
  logout: require("./logout.png"),
  barber_one: require("./barber_one.jpg"),
  barber_two: require("./barber_two.jpg"),
  barber_three: require("./barber_three.jpg"),
  barber_four: require("./barber_four.jpg"),
  close: require("./close.png"),
  camera: require("./camera.png"),
  tcb: require("./TBC1.jpeg"),
  changePassword: require("./changePasswordIcon.png"),
  getStartedScreen: require("./finalSplash.png"),
  background_appo: require("./basho.jpeg"),
};
